// GENERATED by scripts/generate-migrations.mjs — do not edit by hand.
// Source of truth: ../migrations/*.sql. Run `pnpm migrations:generate` after editing one.
//
// The SQL is compiled in rather than read off disk so this package bundles with zero externals
// (docs/bundling.md). `name` is the ledger key written to `skein_migrations` — it matches the
// filename stem node-pg-migrate used before 0.10.0, so existing databases upgrade in place.

/** One schema migration, applied in array order and recorded in `skein_migrations` by `name`. */
export interface SkeinMigration {
  /** Ledger key. Must never change for an already-released migration. */
  readonly name: string;
  /** The up SQL, executed as a single multi-statement query. */
  readonly up: string;
}

const MIGRATION_0001_INIT = `-- Up Migration
--
-- The base schema deliberately does NOT require pgvector, so skein runs on a stock managed
-- Postgres (e.g. Railway's default) out of the box. Semantic search is opt-in: when a store index
-- is configured, \`PostgresSkeinStore.migrate()\` adds the \`vector\` extension and the \`embedding\`
-- column on top of this schema (see postgres-skein-store.ts). Everything below is pgvector-free.

-- Assistants derived from langgraph.json graphs, plus user-created ones.
CREATE TABLE assistants (
  assistant_id text PRIMARY KEY,
  graph_id     text        NOT NULL,
  name         text        NOT NULL,
  description  text,
  config       jsonb       NOT NULL DEFAULT '{}'::jsonb,
  context      jsonb       NOT NULL DEFAULT '{}'::jsonb,
  metadata     jsonb       NOT NULL DEFAULT '{}'::jsonb,
  version      integer     NOT NULL DEFAULT 1,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);

-- Threads: metadata + status, plus the graph state values/interrupts mirrored onto the row.
CREATE TABLE threads (
  thread_id        text        PRIMARY KEY,
  status           text        NOT NULL DEFAULT 'idle',
  metadata         jsonb       NOT NULL DEFAULT '{}'::jsonb,
  values           jsonb       NOT NULL DEFAULT '{}'::jsonb,
  interrupts       jsonb       NOT NULL DEFAULT '{}'::jsonb,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  state_updated_at timestamptz NOT NULL DEFAULT now()
);

-- Runs: status + the opaque execution payload (kwargs). Deleting a thread cascades to its runs.
CREATE TABLE runs (
  run_id             text        PRIMARY KEY,
  thread_id          text        NOT NULL REFERENCES threads (thread_id) ON DELETE CASCADE,
  assistant_id       text        NOT NULL,
  status             text        NOT NULL DEFAULT 'pending',
  metadata           jsonb       NOT NULL DEFAULT '{}'::jsonb,
  multitask_strategy text,
  kwargs             jsonb,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX runs_thread_id_idx ON runs (thread_id);

-- Long-term store items. Without a configured store index, search falls back to naive text
-- matching (matching the memory driver) and no pgvector is needed. When an index IS configured,
-- migrate() adds an unindexed dimensionless \`embedding vector\` column here and populates it so
-- semantic search can rank by cosine distance.
CREATE TABLE store_items (
  namespace  text[]      NOT NULL,
  key        text        NOT NULL,
  value      jsonb       NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (namespace, key)
);
`;

const MIGRATION_0002_STORE_TTL = `-- Up Migration
--
-- Store-item TTL. \`expires_at\` is when the item should be treated as gone; the background sweeper
-- deletes rows past it, and reads filter them out lazily. \`ttl_minutes\` is the item's own lifetime,
-- kept so a refresh-on-read can re-derive \`expires_at = now() + ttl_minutes\`. Both are NULL for
-- items with no TTL (the default), so existing rows are unaffected.

ALTER TABLE store_items ADD COLUMN ttl_minutes double precision;
ALTER TABLE store_items ADD COLUMN expires_at  timestamptz;

CREATE INDEX store_items_expires_at_idx ON store_items (expires_at) WHERE expires_at IS NOT NULL;
`;

const MIGRATION_0003_ASSISTANT_VERSIONS = `-- Up Migration
--
-- Assistant version history. Every \`PATCH /assistants/{id}\` mints a new immutable snapshot here; the
-- live \`assistants\` row keeps \`version\` pointing at the currently-active one and mirrors its fields
-- (so existing readers and the run engine are unchanged). \`setLatest\` rolls the live row back to an
-- existing snapshot without adding a new one. Deleting an assistant cascades to its versions.

CREATE TABLE assistant_versions (
  assistant_id text        NOT NULL REFERENCES assistants (assistant_id) ON DELETE CASCADE,
  version      integer     NOT NULL,
  graph_id     text        NOT NULL,
  name         text        NOT NULL,
  description  text,
  config       jsonb       NOT NULL DEFAULT '{}'::jsonb,
  context      jsonb       NOT NULL DEFAULT '{}'::jsonb,
  metadata     jsonb       NOT NULL DEFAULT '{}'::jsonb,
  created_at   timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (assistant_id, version)
);

-- getVersions filters history by assistant_id and orders by version desc.
CREATE INDEX assistant_versions_assistant_id_idx ON assistant_versions (assistant_id);
`;

const MIGRATION_0004_RUN_ERROR = `-- Up Migration
--
-- Why a run failed, on the run row — and on the thread row, matching the SDK's \`Thread.error\`.
--
-- Before this, a failed run stored only \`status = 'error'\`; the message lived in the thread's
-- \`metadata.error\`, which the next successful run clears. So \`GET /threads/{tid}/runs/{rid}\` could
-- never say what went wrong after the fact, and the message existed in-band only for as long as the
-- SSE stream was open.
--
-- \`runs.error\` holds the JSON-safe \`RunError\` (\`{ error, message, name, cause?, errors?, stack? }\`)
-- — the same payload the \`error\` SSE frame carries, so the stream and the run row can never
-- disagree. \`threads.error\` is the human-readable message only: the thread mirrors the *latest*
-- turn, while the run row is the durable per-run record.
--
-- Both are NULL for every run and thread that did not fail, including every existing row, so this
-- is a pure add with no backfill.

ALTER TABLE runs ADD COLUMN error jsonb;
ALTER TABLE threads ADD COLUMN error text;
`;

/** Every migration, oldest first. Order is the contract — never reorder or rename. */
export const SKEIN_MIGRATIONS: readonly SkeinMigration[] = [
  { name: "0001_init", up: MIGRATION_0001_INIT },
  { name: "0002_store_ttl", up: MIGRATION_0002_STORE_TTL },
  { name: "0003_assistant_versions", up: MIGRATION_0003_ASSISTANT_VERSIONS },
  { name: "0004_run_error", up: MIGRATION_0004_RUN_ERROR },
];
