// GENERATED by scripts/generate-migrations.mjs — do not edit by hand.
// Source of truth: ../migrations/*.sql. Run `pnpm migrations:generate` after editing one.
//
// The SQL is compiled in rather than read off disk so this package bundles with zero externals
// (docs/bundling.md). `name` is the ledger key written to `skein_migrations` — it matches the
// filename stem node-pg-migrate used before 0.10.0, so existing databases upgrade in place.

/** One schema migration, applied in array order and recorded in `skein_migrations` by `name`. */
export interface SkeinMigration {
  /** Ledger key. Must never change for an already-released migration. */
  readonly name: string;
  /** The up SQL, executed as a single multi-statement query. */
  readonly up: string;
  /**
   * Present when the migration is marked `-- skein:concurrent`: `up` pre-split into single
   * statements, to be run one at a time *outside* any transaction.
   *
   * `CREATE INDEX CONCURRENTLY` is rejected inside a transaction block, and `pg`'s simple query
   * protocol wraps a multi-statement string in an implicit one — so these cannot go through the
   * normal BEGIN/COMMIT path. Split at generate time so a malformed one fails the build.
   */
  readonly statements?: readonly string[];
}

const MIGRATION_0001_INIT = `-- Up Migration
--
-- The base schema deliberately does NOT require pgvector, so skein runs on a stock managed
-- Postgres (e.g. Railway's default) out of the box. Semantic search is opt-in: when a store index
-- is configured, \`PostgresSkeinStore.migrate()\` adds the \`vector\` extension and the \`embedding\`
-- column on top of this schema (see postgres-skein-store.ts). Everything below is pgvector-free.

-- Assistants derived from langgraph.json graphs, plus user-created ones.
CREATE TABLE assistants (
  assistant_id text PRIMARY KEY,
  graph_id     text        NOT NULL,
  name         text        NOT NULL,
  description  text,
  config       jsonb       NOT NULL DEFAULT '{}'::jsonb,
  context      jsonb       NOT NULL DEFAULT '{}'::jsonb,
  metadata     jsonb       NOT NULL DEFAULT '{}'::jsonb,
  version      integer     NOT NULL DEFAULT 1,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);

-- Threads: metadata + status, plus the graph state values/interrupts mirrored onto the row.
CREATE TABLE threads (
  thread_id        text        PRIMARY KEY,
  status           text        NOT NULL DEFAULT 'idle',
  metadata         jsonb       NOT NULL DEFAULT '{}'::jsonb,
  values           jsonb       NOT NULL DEFAULT '{}'::jsonb,
  interrupts       jsonb       NOT NULL DEFAULT '{}'::jsonb,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  state_updated_at timestamptz NOT NULL DEFAULT now()
);

-- Runs: status + the opaque execution payload (kwargs). Deleting a thread cascades to its runs.
CREATE TABLE runs (
  run_id             text        PRIMARY KEY,
  thread_id          text        NOT NULL REFERENCES threads (thread_id) ON DELETE CASCADE,
  assistant_id       text        NOT NULL,
  status             text        NOT NULL DEFAULT 'pending',
  metadata           jsonb       NOT NULL DEFAULT '{}'::jsonb,
  multitask_strategy text,
  kwargs             jsonb,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX runs_thread_id_idx ON runs (thread_id);

-- Long-term store items. Without a configured store index, search falls back to naive text
-- matching (matching the memory driver) and no pgvector is needed. When an index IS configured,
-- migrate() adds an unindexed dimensionless \`embedding vector\` column here and populates it so
-- semantic search can rank by cosine distance.
CREATE TABLE store_items (
  namespace  text[]      NOT NULL,
  key        text        NOT NULL,
  value      jsonb       NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (namespace, key)
);
`;

const MIGRATION_0002_STORE_TTL = `-- Up Migration
--
-- Store-item TTL. \`expires_at\` is when the item should be treated as gone; the background sweeper
-- deletes rows past it, and reads filter them out lazily. \`ttl_minutes\` is the item's own lifetime,
-- kept so a refresh-on-read can re-derive \`expires_at = now() + ttl_minutes\`. Both are NULL for
-- items with no TTL (the default), so existing rows are unaffected.

ALTER TABLE store_items ADD COLUMN ttl_minutes double precision;
ALTER TABLE store_items ADD COLUMN expires_at  timestamptz;

CREATE INDEX store_items_expires_at_idx ON store_items (expires_at) WHERE expires_at IS NOT NULL;
`;

const MIGRATION_0003_ASSISTANT_VERSIONS = `-- Up Migration
--
-- Assistant version history. Every \`PATCH /assistants/{id}\` mints a new immutable snapshot here; the
-- live \`assistants\` row keeps \`version\` pointing at the currently-active one and mirrors its fields
-- (so existing readers and the run engine are unchanged). \`setLatest\` rolls the live row back to an
-- existing snapshot without adding a new one. Deleting an assistant cascades to its versions.

CREATE TABLE assistant_versions (
  assistant_id text        NOT NULL REFERENCES assistants (assistant_id) ON DELETE CASCADE,
  version      integer     NOT NULL,
  graph_id     text        NOT NULL,
  name         text        NOT NULL,
  description  text,
  config       jsonb       NOT NULL DEFAULT '{}'::jsonb,
  context      jsonb       NOT NULL DEFAULT '{}'::jsonb,
  metadata     jsonb       NOT NULL DEFAULT '{}'::jsonb,
  created_at   timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (assistant_id, version)
);

-- getVersions filters history by assistant_id and orders by version desc.
CREATE INDEX assistant_versions_assistant_id_idx ON assistant_versions (assistant_id);
`;

const MIGRATION_0004_RUN_ERROR = `-- Up Migration
--
-- Why a run failed, on the run row — and on the thread row, matching the SDK's \`Thread.error\`.
--
-- Before this, a failed run stored only \`status = 'error'\`; the message lived in the thread's
-- \`metadata.error\`, which the next successful run clears. So \`GET /threads/{tid}/runs/{rid}\` could
-- never say what went wrong after the fact, and the message existed in-band only for as long as the
-- SSE stream was open.
--
-- \`runs.error\` holds the JSON-safe \`RunError\` (\`{ error, message, name, cause?, errors?, stack? }\`)
-- — the same payload the \`error\` SSE frame carries, so the stream and the run row can never
-- disagree. \`threads.error\` is the human-readable message only: the thread mirrors the *latest*
-- turn, while the run row is the durable per-run record.
--
-- Both are NULL for every run and thread that did not fail, including every existing row, so this
-- is a pure add with no backfill.

ALTER TABLE runs ADD COLUMN error jsonb;
ALTER TABLE threads ADD COLUMN error text;
`;

const MIGRATION_0005_PERFORMANCE_INDEXES = `-- Up Migration
-- skein:concurrent
--
-- Indexes for the list/search paths. Until now the schema had exactly three indexes
-- (runs_thread_id_idx, store_items_expires_at_idx, assistant_versions_assistant_id_idx), so every
-- \`POST /threads/search\` was a sequential scan plus a sort, and every \`metadata @> …\` filter — the
-- shape the auth ownership check uses on every request — was a sequential scan against jsonb.
--
-- \`skein:concurrent\` (read by scripts/generate-migrations.mjs) runs each statement outside a
-- transaction, one at a time. CREATE INDEX CONCURRENTLY cannot run inside a transaction block, and a
-- plain CREATE INDEX would hold a write-blocking lock for the whole build — on a large existing
-- \`threads\` table that is a multi-minute stall at boot, during a rolling deploy, which is exactly
-- when it must not happen.
--
-- Every statement is IF NOT EXISTS so a partially-applied run can be retried: the ledger row is only
-- written once all of them succeed. One Postgres wart to know about — a CONCURRENTLY build that
-- fails leaves an *invalid* index behind, and IF NOT EXISTS will then skip it forever. See
-- docs/storage.md for how to spot and drop one.

-- The default thread sort. Composite because the query always orders by \`<sortBy>, thread_id\` — the
-- tiebreaker that makes OFFSET paging stable — so a lone created_at index would still sort.
CREATE INDEX CONCURRENTLY IF NOT EXISTS threads_created_at_thread_id_idx
  ON threads (created_at, thread_id);

-- \`sortBy: "updated_at"\`, the other sort the search surface accepts.
CREATE INDEX CONCURRENTLY IF NOT EXISTS threads_updated_at_thread_id_idx
  ON threads (updated_at, thread_id);

-- \`WHERE status = $n ORDER BY created_at\`. Status leads so the equality filter can use the index and
-- still get ordered rows out of it; status alone has too few distinct values to be worth indexing.
CREATE INDEX CONCURRENTLY IF NOT EXISTS threads_status_created_at_idx
  ON threads (status, created_at);

-- \`metadata @> $n::jsonb\`. GIN with jsonb_path_ops rather than the default: containment is the only
-- operator skein uses on this column, and path_ops is smaller and faster for it.
CREATE INDEX CONCURRENTLY IF NOT EXISTS threads_metadata_idx
  ON threads USING gin (metadata jsonb_path_ops);

CREATE INDEX CONCURRENTLY IF NOT EXISTS assistants_metadata_idx
  ON assistants USING gin (metadata jsonb_path_ops);

CREATE INDEX CONCURRENTLY IF NOT EXISTS assistants_created_at_assistant_id_idx
  ON assistants (created_at, assistant_id);

-- \`WHERE thread_id = $1 ORDER BY created_at\`, used by listByThread and listActiveRuns — both on the
-- run-creation path, so this one is hot.
CREATE INDEX CONCURRENTLY IF NOT EXISTS runs_thread_id_created_at_idx
  ON runs (thread_id, created_at);

-- Superseded by the composite above, whose leading column is the same. Kept until now only because
-- nothing else needed changing here; a redundant index costs write amplification on every run.
DROP INDEX CONCURRENTLY IF EXISTS runs_thread_id_idx;

-- The store search's default ordering.
CREATE INDEX CONCURRENTLY IF NOT EXISTS store_items_created_at_key_idx
  ON store_items (created_at, key);
`;

const MIGRATION_0006_INFLIGHT_RUNS_INDEX = `-- Up Migration
-- skein:concurrent
--
-- \`POST /runs/cancel\` with only a status filter sweeps *every* thread's inflight runs
-- (\`RunRepo.listActiveRuns()\` with no thread id). Without an index that is a sequential scan over
-- the whole \`runs\` table plus a sort, on a table that only ever grows — and \`runs\` is the largest
-- table skein writes, one row per turn forever.
--
-- A **partial** index rather than one on \`status\`: inflight is a vanishingly small slice of a mature
-- \`runs\` table (every run ends terminal), so the index stays tiny and its maintenance cost is two
-- entries per run's lifetime — one on insert, one when it settles out of the predicate. An index on
-- all of \`status\` would carry every historical row to serve a query that never wants one.
--
-- The predicate is a literal because Postgres needs one to match a query against it. The queries that
-- must match it (\`listActiveRuns\`, \`hasActiveRun\`, \`createIfThreadIdle\`) therefore filter *positively*
-- with \`status IN ('pending','running')\`, built from \`INFLIGHT_RUN_STATUSES\` — see INFLIGHT_STATUS_SQL.
--
-- A negated, parameterized filter (\`NOT (status = ANY($1))\`) does NOT match: proving it implies this
-- predicate would require enumerating the column's domain, which the planner does not do, and under a
-- generic plan the parameter is not even a constant. That form silently sequential-scans the whole table
-- while still paying this index's write cost — a performance coupling, not a correctness one, and the
-- reason the query and this predicate are both derived from one constant.
--
-- \`skein:concurrent\` for the same reason as 0005: CREATE INDEX CONCURRENTLY cannot run inside a
-- transaction, and a plain build would hold a write-blocking lock on \`runs\` at boot.

CREATE INDEX CONCURRENTLY IF NOT EXISTS runs_inflight_created_at_idx
  ON runs (created_at, run_id)
  WHERE status IN ('pending', 'running');
`;

const MIGRATION_0007_CRONS = `-- Up Migration
--
-- Crons: schedules that fire runs on a cadence (LangGraph Platform's Crons resource).
--
-- The row is the source of truth for the whole wire contract — \`search\` filters and sorts it,
-- \`count\` counts it, \`enabled\` pauses it — and it is *also* the scheduler's coordination
-- mechanism. Both roles are why the schedule lives here rather than in the run queue: a queue can
-- hold a timer, but it cannot serve \`sort_by=next_run_date\` with a metadata filter and an offset.

CREATE TABLE crons (
  cron_id          text        PRIMARY KEY,
  assistant_id     text        NOT NULL,
  -- NULL means a *stateless* cron: every fire creates its own thread. A thread cron cannot outlive
  -- the thread it runs on, so the cascade makes "a cron whose thread is gone" unrepresentable
  -- rather than a case the scheduler has to handle on every occurrence (mirrors runs.thread_id).
  thread_id        text        REFERENCES threads (thread_id) ON DELETE CASCADE,
  schedule         text        NOT NULL,
  timezone         text,
  end_time         timestamptz,
  -- When this cron next fires. NULL means *dormant* — disabled, or no occurrence left before
  -- end_time — which is simultaneously the wire answer and what drops the row out of the partial
  -- index below. Deliberately has NO DEFAULT: it is only ever written from a value skein computed
  -- with a cron parser, never from the database clock.
  next_run_date    timestamptz,
  enabled          boolean     NOT NULL DEFAULT true,
  -- The compare-and-swap token the scheduler claims an occurrence with, bumped on EVERY write.
  --
  -- An integer rather than comparing \`next_run_date\` itself, and that is not a style choice: a
  -- timestamptz carries microseconds, which are truncated on the way back out through a
  -- millisecond \`Date\`, so a timestamp comparison could stop matching and no cron would ever fire
  -- again with nothing logged to say so. An integer also closes the ABA window where a PATCH
  -- recomputes back to the same instant between a scan and its claim.
  occurrence_seq   bigint      NOT NULL DEFAULT 0,
  on_run_completed text,
  payload          jsonb       NOT NULL DEFAULT '{}'::jsonb,
  metadata         jsonb       NOT NULL DEFAULT '{}'::jsonb,
  user_id          text,
  -- The principal a fired run executes as. Beside the row and never on the wire, for the same
  -- reason runs.kwargs is: \`payload\` is echoed to any reader of GET /runs/crons/{id}, and a
  -- caller's permission scopes are not a thing to echo.
  auth             jsonb,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now()
);

-- The scheduler's hot path, run once per tick per instance forever. Partial, because a dormant or
-- disabled cron is dead weight in an index whose only query is "what is due now".
--
-- The predicate is a bare literal, so the due query must filter *positively* with a literal
-- \`WHERE enabled\` — \`enabled = $1\` is a parameter the planner cannot prove implies this predicate,
-- and would sequential-scan while still paying the index's write cost. Same trap 0006 documents.
CREATE INDEX crons_due_idx
  ON crons (next_run_date)
  WHERE enabled;

-- Search filters by assistant, by thread, and by metadata containment. Only the metadata index is
-- worth its write cost up front: crons is a low-cardinality table (schedules are created by hand,
-- not one per turn like runs), so a sequential scan is cheap and sort indexes would be maintenance
-- with no reader. Add composites here if a deployment ever proves a search sort slow.
CREATE INDEX crons_metadata_idx ON crons USING gin (metadata jsonb_path_ops);
`;

const MIGRATION_0008_THREAD_TTL = `-- Up Migration
--
-- Thread TTL. \`expires_at\` is when the thread becomes eligible for deletion; the background sweeper
-- collects rows past it. \`ttl_minutes\` is the thread's own lifetime, kept so the value a caller set
-- is still legible after the fact. Both are NULL for threads with no TTL (the default), so existing
-- rows are unaffected and stay forever.
--
-- Unlike \`store_items\`, reads do NOT filter on \`expires_at\`: expiry here means "may be collected",
-- not "gone". A thread is a container for runs and checkpoints, and hiding one early would make a
-- thread with an in-flight run read as absent while that run was still writing to it.

ALTER TABLE threads ADD COLUMN ttl_minutes double precision;
ALTER TABLE threads ADD COLUMN expires_at  timestamptz;

CREATE INDEX threads_expires_at_idx ON threads (expires_at) WHERE expires_at IS NOT NULL;
`;

const MIGRATION_0009_DROP_REDUNDANT_VERSION_INDEX = `-- Up Migration
-- skein:concurrent
--
-- \`assistant_versions_assistant_id_idx\` (0003) indexes \`(assistant_id)\` on a table whose PRIMARY KEY is
-- already \`(assistant_id, version)\`. A btree with the same leading column is strictly redundant: the PK
-- serves every query the single-column index could, and serves the ones that matter *better*.
--
-- Both real readers want the composite. \`listVersions\` is
-- \`WHERE assistant_id = $1 ORDER BY version DESC\` — the PK gives the filter and the ordering together,
-- where the narrow index gives only the filter and leaves a sort. And the \`ON DELETE CASCADE\` from
-- \`assistants\` looks rows up by \`assistant_id\`, which the PK's leading column answers.
--
-- So its only remaining effect is write amplification: a second index entry to insert on every
-- assistant update (each of which appends an immutable version snapshot) and a second to clean up on
-- every cascade. Same reasoning, and the same fix, as 0005 dropping \`runs_thread_id_idx\`.
--
-- \`skein:concurrent\` because DROP INDEX CONCURRENTLY cannot run inside a transaction — and, unlike a
-- plain DROP, it does not take a lock that blocks reads and writes on \`assistant_versions\` while it runs.

DROP INDEX CONCURRENTLY IF EXISTS assistant_versions_assistant_id_idx;
`;

const MIGRATION_0010_IDEMPOTENCY = `-- Up Migration
--
-- Recorded responses for the \`Idempotency-Key\` header, so a provider's retry of a create gets the
-- original answer instead of a second run.
--
-- Every webhook provider retries — Twilio on timeout or 5xx, Stripe, GitHub, Slack — and without
-- this table each retry means a second reply to the end user, or two agents acting on one event.
-- The row is the arbiter as well as the record: a claim is an INSERT that races on the primary key,
-- so two retries landing on two instances within milliseconds cannot both win.

CREATE TABLE idempotency_records (
  -- What the key is scoped to — "{METHOD} {path} {principal}". The principal is part of the key, not
  -- a filter on top of it: without it, one tenant guessing another's key would replay that tenant's
  -- recorded response, which names a run and a thread they have no other way to see.
  scope       text        NOT NULL,
  -- The caller's header, verbatim. Opaque — never parsed, only compared.
  key         text        NOT NULL,
  -- Hex SHA-256 of the canonicalized request, so the same key sent with a different body is refused
  -- rather than silently answered with the first request's response.
  fingerprint text        NOT NULL,
  -- The token the claiming request holds. \`record\` and \`release\` are conditional on it, so a claim
  -- that expired and was taken over cannot have the original's response written on top of it.
  claim_id    text        NOT NULL,
  -- 'in_flight' | 'done'. There is deliberately no 'failed': a recorded failure would pin a
  -- transient 503 for the whole retention, making a momentary outage permanent for that key.
  status      text        NOT NULL,
  -- The verbatim wire response, present only once status is 'done'. Carries the headers as well as
  -- the body — \`content-location\` is what the SDK reads to fire \`onRunCreated\`, and a replay that
  -- drops it leaves \`useStream\` unable to rejoin after a remount.
  response    jsonb,
  -- Deliberately NO foreign key. A replay has to keep working after its run is gone: a stateless
  -- run's server-created thread is deleted on completion and would cascade this record away with it,
  -- which is exactly the retry window this table exists to cover.
  run_id      text,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  -- When this record stops being replayable. Written short at claim time (the in-flight window) and
  -- extended to the full retention when the response is recorded, so one column covers both "the
  -- claiming instance died" and "the dedup window is over".
  expires_at  timestamptz NOT NULL,
  -- This composite key IS the constraint a claim races on — there is no separate unique index. An
  -- insert-first claim lets Postgres arbitrate; a read-then-write pair has a window, and that window
  -- is precisely the double-delivery burst this table defends against.
  PRIMARY KEY (scope, key)
);

-- The sweeper's only query. Unconditional rather than partial (unlike store_items_expires_at_idx):
-- every row here has an expiry, so a predicate would exclude nothing and only cost planning.
CREATE INDEX idempotency_records_expires_at_idx ON idempotency_records (expires_at);
`;

/** Every migration, oldest first. Order is the contract — never reorder or rename. */
export const SKEIN_MIGRATIONS: readonly SkeinMigration[] = [
  { name: "0001_init", up: MIGRATION_0001_INIT },
  { name: "0002_store_ttl", up: MIGRATION_0002_STORE_TTL },
  { name: "0003_assistant_versions", up: MIGRATION_0003_ASSISTANT_VERSIONS },
  { name: "0004_run_error", up: MIGRATION_0004_RUN_ERROR },
  {
    name: "0005_performance_indexes",
    up: MIGRATION_0005_PERFORMANCE_INDEXES,
    statements: [
      `CREATE INDEX CONCURRENTLY IF NOT EXISTS threads_created_at_thread_id_idx
  ON threads (created_at, thread_id)`,
      `CREATE INDEX CONCURRENTLY IF NOT EXISTS threads_updated_at_thread_id_idx
  ON threads (updated_at, thread_id)`,
      `CREATE INDEX CONCURRENTLY IF NOT EXISTS threads_status_created_at_idx
  ON threads (status, created_at)`,
      `CREATE INDEX CONCURRENTLY IF NOT EXISTS threads_metadata_idx
  ON threads USING gin (metadata jsonb_path_ops)`,
      `CREATE INDEX CONCURRENTLY IF NOT EXISTS assistants_metadata_idx
  ON assistants USING gin (metadata jsonb_path_ops)`,
      `CREATE INDEX CONCURRENTLY IF NOT EXISTS assistants_created_at_assistant_id_idx
  ON assistants (created_at, assistant_id)`,
      `CREATE INDEX CONCURRENTLY IF NOT EXISTS runs_thread_id_created_at_idx
  ON runs (thread_id, created_at)`,
      `DROP INDEX CONCURRENTLY IF EXISTS runs_thread_id_idx`,
      `CREATE INDEX CONCURRENTLY IF NOT EXISTS store_items_created_at_key_idx
  ON store_items (created_at, key)`,
    ],
  },
  {
    name: "0006_inflight_runs_index",
    up: MIGRATION_0006_INFLIGHT_RUNS_INDEX,
    statements: [
      `CREATE INDEX CONCURRENTLY IF NOT EXISTS runs_inflight_created_at_idx
  ON runs (created_at, run_id)
  WHERE status IN ('pending', 'running')`,
    ],
  },
  { name: "0007_crons", up: MIGRATION_0007_CRONS },
  { name: "0008_thread_ttl", up: MIGRATION_0008_THREAD_TTL },
  {
    name: "0009_drop_redundant_version_index",
    up: MIGRATION_0009_DROP_REDUNDANT_VERSION_INDEX,
    statements: [`DROP INDEX CONCURRENTLY IF EXISTS assistant_versions_assistant_id_idx`],
  },
  { name: "0010_idempotency", up: MIGRATION_0010_IDEMPOTENCY },
];
