// GENERATED by scripts/generate-migrations.mjs — do not edit by hand.
// Source of truth: ../migrations/*.sql. Run `pnpm migrations:generate` after editing one.
//
// The SQL is compiled in rather than read off disk so this package bundles with zero externals
// (docs/bundling.md). `name` is the ledger key written to `skein_migrations` — it matches the
// filename stem node-pg-migrate used before 0.10.0, so existing databases upgrade in place.

/** One schema migration, applied in array order and recorded in `skein_migrations` by `name`. */
export interface SkeinMigration {
  /** Ledger key. Must never change for an already-released migration. */
  readonly name: string;
  /** The up SQL, executed as a single multi-statement query. */
  readonly up: string;
  /**
   * Present when the migration is marked `-- skein:concurrent`: `up` pre-split into single
   * statements, to be run one at a time *outside* any transaction.
   *
   * `CREATE INDEX CONCURRENTLY` is rejected inside a transaction block, and `pg`'s simple query
   * protocol wraps a multi-statement string in an implicit one — so these cannot go through the
   * normal BEGIN/COMMIT path. Split at generate time so a malformed one fails the build.
   */
  readonly statements?: readonly string[];
}

const MIGRATION_0001_INIT = `-- Up Migration
--
-- The base schema deliberately does NOT require pgvector, so skein runs on a stock managed
-- Postgres (e.g. Railway's default) out of the box. Semantic search is opt-in: when a store index
-- is configured, \`PostgresSkeinStore.migrate()\` adds the \`vector\` extension and the \`embedding\`
-- column on top of this schema (see postgres-skein-store.ts). Everything below is pgvector-free.

-- Assistants derived from langgraph.json graphs, plus user-created ones.
CREATE TABLE assistants (
  assistant_id text PRIMARY KEY,
  graph_id     text        NOT NULL,
  name         text        NOT NULL,
  description  text,
  config       jsonb       NOT NULL DEFAULT '{}'::jsonb,
  context      jsonb       NOT NULL DEFAULT '{}'::jsonb,
  metadata     jsonb       NOT NULL DEFAULT '{}'::jsonb,
  version      integer     NOT NULL DEFAULT 1,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);

-- Threads: metadata + status, plus the graph state values/interrupts mirrored onto the row.
CREATE TABLE threads (
  thread_id        text        PRIMARY KEY,
  status           text        NOT NULL DEFAULT 'idle',
  metadata         jsonb       NOT NULL DEFAULT '{}'::jsonb,
  values           jsonb       NOT NULL DEFAULT '{}'::jsonb,
  interrupts       jsonb       NOT NULL DEFAULT '{}'::jsonb,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  state_updated_at timestamptz NOT NULL DEFAULT now()
);

-- Runs: status + the opaque execution payload (kwargs). Deleting a thread cascades to its runs.
CREATE TABLE runs (
  run_id             text        PRIMARY KEY,
  thread_id          text        NOT NULL REFERENCES threads (thread_id) ON DELETE CASCADE,
  assistant_id       text        NOT NULL,
  status             text        NOT NULL DEFAULT 'pending',
  metadata           jsonb       NOT NULL DEFAULT '{}'::jsonb,
  multitask_strategy text,
  kwargs             jsonb,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX runs_thread_id_idx ON runs (thread_id);

-- Long-term store items. Without a configured store index, search falls back to naive text
-- matching (matching the memory driver) and no pgvector is needed. When an index IS configured,
-- migrate() adds an unindexed dimensionless \`embedding vector\` column here and populates it so
-- semantic search can rank by cosine distance.
CREATE TABLE store_items (
  namespace  text[]      NOT NULL,
  key        text        NOT NULL,
  value      jsonb       NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (namespace, key)
);
`;

const MIGRATION_0002_STORE_TTL = `-- Up Migration
--
-- Store-item TTL. \`expires_at\` is when the item should be treated as gone; the background sweeper
-- deletes rows past it, and reads filter them out lazily. \`ttl_minutes\` is the item's own lifetime,
-- kept so a refresh-on-read can re-derive \`expires_at = now() + ttl_minutes\`. Both are NULL for
-- items with no TTL (the default), so existing rows are unaffected.

ALTER TABLE store_items ADD COLUMN ttl_minutes double precision;
ALTER TABLE store_items ADD COLUMN expires_at  timestamptz;

CREATE INDEX store_items_expires_at_idx ON store_items (expires_at) WHERE expires_at IS NOT NULL;
`;

const MIGRATION_0003_ASSISTANT_VERSIONS = `-- Up Migration
--
-- Assistant version history. Every \`PATCH /assistants/{id}\` mints a new immutable snapshot here; the
-- live \`assistants\` row keeps \`version\` pointing at the currently-active one and mirrors its fields
-- (so existing readers and the run engine are unchanged). \`setLatest\` rolls the live row back to an
-- existing snapshot without adding a new one. Deleting an assistant cascades to its versions.

CREATE TABLE assistant_versions (
  assistant_id text        NOT NULL REFERENCES assistants (assistant_id) ON DELETE CASCADE,
  version      integer     NOT NULL,
  graph_id     text        NOT NULL,
  name         text        NOT NULL,
  description  text,
  config       jsonb       NOT NULL DEFAULT '{}'::jsonb,
  context      jsonb       NOT NULL DEFAULT '{}'::jsonb,
  metadata     jsonb       NOT NULL DEFAULT '{}'::jsonb,
  created_at   timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (assistant_id, version)
);

-- getVersions filters history by assistant_id and orders by version desc.
CREATE INDEX assistant_versions_assistant_id_idx ON assistant_versions (assistant_id);
`;

const MIGRATION_0004_RUN_ERROR = `-- Up Migration
--
-- Why a run failed, on the run row — and on the thread row, matching the SDK's \`Thread.error\`.
--
-- Before this, a failed run stored only \`status = 'error'\`; the message lived in the thread's
-- \`metadata.error\`, which the next successful run clears. So \`GET /threads/{tid}/runs/{rid}\` could
-- never say what went wrong after the fact, and the message existed in-band only for as long as the
-- SSE stream was open.
--
-- \`runs.error\` holds the JSON-safe \`RunError\` (\`{ error, message, name, cause?, errors?, stack? }\`)
-- — the same payload the \`error\` SSE frame carries, so the stream and the run row can never
-- disagree. \`threads.error\` is the human-readable message only: the thread mirrors the *latest*
-- turn, while the run row is the durable per-run record.
--
-- Both are NULL for every run and thread that did not fail, including every existing row, so this
-- is a pure add with no backfill.

ALTER TABLE runs ADD COLUMN error jsonb;
ALTER TABLE threads ADD COLUMN error text;
`;

const MIGRATION_0005_PERFORMANCE_INDEXES = `-- Up Migration
-- skein:concurrent
--
-- Indexes for the list/search paths. Until now the schema had exactly three indexes
-- (runs_thread_id_idx, store_items_expires_at_idx, assistant_versions_assistant_id_idx), so every
-- \`POST /threads/search\` was a sequential scan plus a sort, and every \`metadata @> …\` filter — the
-- shape the auth ownership check uses on every request — was a sequential scan against jsonb.
--
-- \`skein:concurrent\` (read by scripts/generate-migrations.mjs) runs each statement outside a
-- transaction, one at a time. CREATE INDEX CONCURRENTLY cannot run inside a transaction block, and a
-- plain CREATE INDEX would hold a write-blocking lock for the whole build — on a large existing
-- \`threads\` table that is a multi-minute stall at boot, during a rolling deploy, which is exactly
-- when it must not happen.
--
-- Every statement is IF NOT EXISTS so a partially-applied run can be retried: the ledger row is only
-- written once all of them succeed. One Postgres wart to know about — a CONCURRENTLY build that
-- fails leaves an *invalid* index behind, and IF NOT EXISTS will then skip it forever. See
-- docs/storage.md for how to spot and drop one.

-- The default thread sort. Composite because the query always orders by \`<sortBy>, thread_id\` — the
-- tiebreaker that makes OFFSET paging stable — so a lone created_at index would still sort.
CREATE INDEX CONCURRENTLY IF NOT EXISTS threads_created_at_thread_id_idx
  ON threads (created_at, thread_id);

-- \`sortBy: "updated_at"\`, the other sort the search surface accepts.
CREATE INDEX CONCURRENTLY IF NOT EXISTS threads_updated_at_thread_id_idx
  ON threads (updated_at, thread_id);

-- \`WHERE status = $n ORDER BY created_at\`. Status leads so the equality filter can use the index and
-- still get ordered rows out of it; status alone has too few distinct values to be worth indexing.
CREATE INDEX CONCURRENTLY IF NOT EXISTS threads_status_created_at_idx
  ON threads (status, created_at);

-- \`metadata @> $n::jsonb\`. GIN with jsonb_path_ops rather than the default: containment is the only
-- operator skein uses on this column, and path_ops is smaller and faster for it.
CREATE INDEX CONCURRENTLY IF NOT EXISTS threads_metadata_idx
  ON threads USING gin (metadata jsonb_path_ops);

CREATE INDEX CONCURRENTLY IF NOT EXISTS assistants_metadata_idx
  ON assistants USING gin (metadata jsonb_path_ops);

CREATE INDEX CONCURRENTLY IF NOT EXISTS assistants_created_at_assistant_id_idx
  ON assistants (created_at, assistant_id);

-- \`WHERE thread_id = $1 ORDER BY created_at\`, used by listByThread and listActiveRuns — both on the
-- run-creation path, so this one is hot.
CREATE INDEX CONCURRENTLY IF NOT EXISTS runs_thread_id_created_at_idx
  ON runs (thread_id, created_at);

-- Superseded by the composite above, whose leading column is the same. Kept until now only because
-- nothing else needed changing here; a redundant index costs write amplification on every run.
DROP INDEX CONCURRENTLY IF EXISTS runs_thread_id_idx;

-- The store search's default ordering.
CREATE INDEX CONCURRENTLY IF NOT EXISTS store_items_created_at_key_idx
  ON store_items (created_at, key);
`;

/** Every migration, oldest first. Order is the contract — never reorder or rename. */
export const SKEIN_MIGRATIONS: readonly SkeinMigration[] = [
  { name: "0001_init", up: MIGRATION_0001_INIT },
  { name: "0002_store_ttl", up: MIGRATION_0002_STORE_TTL },
  { name: "0003_assistant_versions", up: MIGRATION_0003_ASSISTANT_VERSIONS },
  { name: "0004_run_error", up: MIGRATION_0004_RUN_ERROR },
  {
    name: "0005_performance_indexes",
    up: MIGRATION_0005_PERFORMANCE_INDEXES,
    statements: [
      `CREATE INDEX CONCURRENTLY IF NOT EXISTS threads_created_at_thread_id_idx
  ON threads (created_at, thread_id)`,
      `CREATE INDEX CONCURRENTLY IF NOT EXISTS threads_updated_at_thread_id_idx
  ON threads (updated_at, thread_id)`,
      `CREATE INDEX CONCURRENTLY IF NOT EXISTS threads_status_created_at_idx
  ON threads (status, created_at)`,
      `CREATE INDEX CONCURRENTLY IF NOT EXISTS threads_metadata_idx
  ON threads USING gin (metadata jsonb_path_ops)`,
      `CREATE INDEX CONCURRENTLY IF NOT EXISTS assistants_metadata_idx
  ON assistants USING gin (metadata jsonb_path_ops)`,
      `CREATE INDEX CONCURRENTLY IF NOT EXISTS assistants_created_at_assistant_id_idx
  ON assistants (created_at, assistant_id)`,
      `CREATE INDEX CONCURRENTLY IF NOT EXISTS runs_thread_id_created_at_idx
  ON runs (thread_id, created_at)`,
      `DROP INDEX CONCURRENTLY IF EXISTS runs_thread_id_idx`,
      `CREATE INDEX CONCURRENTLY IF NOT EXISTS store_items_created_at_key_idx
  ON store_items (created_at, key)`,
    ],
  },
];
