// Flat ESLint config for the skein-js workspace.
// ESLint owns correctness + imports; Prettier owns formatting (eslint-config-prettier
// disables any stylistic rules that would fight the formatter). See docs/code-practices.md.
import js from "@eslint/js";
import tseslint from "typescript-eslint";
import importPlugin from "eslint-plugin-import";
import unusedImports from "eslint-plugin-unused-imports";
import prettier from "eslint-config-prettier";

export default tseslint.config(
  {
    ignores: [
      "**/dist/**",
      // `skein build` output inside an example. Git already ignores `.skein/`, so a developer who has
      // run a local build otherwise fails `pnpm lint` on bundled third-party code they did not write.
      "**/.skein/**",
      "**/.next/**",
      // VitePress's prebundled dependencies. `.gitignore` covers it, but flat config doesn't read
      // that — so without this, a developer who has run `pnpm docs:build` fails `pnpm lint` on a
      // vendored MiniSearch bundle.
      "docs/.vitepress/cache/**",
      // VitePress bundles `config.mts` to a throwaway `config.mts.timestamp-<ms>-<hash>.mjs` beside
      // it and unlinks it moments later. `*.config.*` above does not match that name (nothing
      // precedes `config.`), so a `lint` running concurrently with `build` — which is every
      // `run-many` — could enumerate the file and then fail ENOENT reading a file that no longer
      // exists. Nothing here is ours to lint either way.
      "**/*.timestamp-*.mjs",
      "**/next-env.d.ts", // generated by Next.js; its triple-slash reference is not ours to fix
      "**/node_modules/**",
      "**/.nx/**",
      "**/*.config.*",
      "packages/cli/src/bundle/__fixtures__/**", // mini-monorepo fixture shaped for the bundler, not our lint rules
      // Throwaway projects a test writes into its own package directory, because a fixture that
      // declares an `auth.path` has to sit somewhere node resolution can reach the workspace's
      // `node_modules`. They are deleted in `afterAll`, but a lint running alongside the suite would
      // otherwise pick them up mid-flight and fail on generated code nobody wrote.
      "**/.tmp-*/**",
      "packages/test-support/fixtures/**", // project/artifact fixtures shaped for the image build, same reason
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    plugins: {
      import: importPlugin,
      "unused-imports": unusedImports,
    },
    rules: {
      // --- functional / simplicity leanings (see docs/code-practices.md §2–3) ---
      "prefer-const": "error",
      "no-var": "error",
      "no-param-reassign": "error",
      eqeqeq: ["error", "always", { null: "ignore" }],
      "object-shorthand": ["error", "always"],

      // --- named exports only in library code ---
      "import/no-default-export": "error",

      // --- tidy imports ---
      "unused-imports/no-unused-imports": "error",
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      "import/order": [
        "warn",
        {
          "newlines-between": "always",
          alphabetize: { order: "asc", caseInsensitive: true },
          groups: ["builtin", "external", "internal", "parent", "sibling", "index"],
        },
      ],

      // --- explicitness ---
      "@typescript-eslint/consistent-type-imports": [
        "error",
        { prefer: "type-imports", fixStyle: "inline-type-imports" },
      ],
      "@typescript-eslint/no-explicit-any": "warn",
    },
  },

  // Frameworks that REQUIRE default exports (Next.js pages/layouts/route configs, config files).
  // (The console SPA needs the same exemption, but it owns a per-project config — see
  // packages/console/ui/eslint.config.mjs — where `files` patterns resolve relative to *that*
  // directory, so listing it here would silently never match.)
  {
    files: [
      "examples/react-usestream/**/*.{ts,tsx}",
      "examples/chat-app/**/*.{ts,tsx}",
      "examples/nextjs-basic/**/*.{ts,tsx}",
      "examples/nextjs-app/**/*.{ts,tsx}",
      "**/*.config.{ts,mts,mjs}",
      // VitePress: the site config and the theme entry are both default-export contracts. Note the
      // `*.config.*` pattern above does NOT cover `docs/.vitepress/config.mts` — that glob needs a
      // segment before `.config`, and this file is named plain `config.mts`.
      "docs/.vitepress/**/*.{ts,mts}",
    ],
    rules: { "import/no-default-export": "off" },
  },

  // Build-time codegen and test-harness scripts run in Node, not in the library sandbox — they may use
  // the console, the filesystem, timers, and fetch freely. Globals are enumerated rather than pulled
  // from the `globals` package, which is only a transitive dependency here.
  // (Root-level scripts/ isn't linted at all; it belongs to no project.)
  {
    files: ["packages/*/scripts/**/*.mjs"],
    languageOptions: {
      globals: {
        console: "readonly",
        process: "readonly",
        fetch: "readonly",
        AbortSignal: "readonly",
        URL: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
      },
    },
  },

  // Fixtures that stand in for build output — a `skein build` artifact's compiled JS graphs. They are
  // plain Node modules by definition (see packages/test-support/fixtures/runtime-artifact/README.md),
  // so they get Node's globals rather than the library sandbox's.
  {
    files: ["packages/*/fixtures/**/*.js"],
    languageOptions: {
      globals: { process: "readonly", setTimeout: "readonly", console: "readonly" },
    },
  },

  // @skein-js/storage-postgres must stay bundleable: it is the driver that framework adapters and
  // embedPostgresGraphs pull into a downstream bundle, and it used to read its own migrations/ dir
  // via import.meta.url — which bundlers rewrite to the output location, breaking at runtime. The
  // SQL now ships compiled in (src/migrations.generated.ts), and these rules are what keep it that
  // way. Tests are exempt: the drift test legitimately reads the .sql files. See docs/bundling.md.
  {
    files: ["packages/storage-postgres/src/**/*.ts"],
    ignores: ["packages/storage-postgres/src/**/*.test.ts"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          // Patterns, not exact `paths`: `fs/promises` and `node:fs/promises` are the same hazard,
          // and `node:module` (createRequire) is a back door to the same filesystem access.
          patterns: [
            {
              group: [
                "fs",
                "fs/*",
                "path",
                "path/*",
                "url",
                "module",
                "node:fs",
                "node:fs/*",
                "node:path",
                "node:path/*",
                "node:url",
                "node:module",
              ],
              message:
                "storage-postgres must not touch the filesystem — it has to bundle with zero " +
                "externals (docs/bundling.md). Compile the asset in instead, as migrations/*.sql are.",
            },
          ],
        },
      ],
      "no-restricted-syntax": [
        "error",
        {
          // Any property of import.meta, not just `url`: import.meta.dirname and .filename are
          // rewritten to the bundle location exactly the same way.
          selector: "MetaProperty",
          message:
            "import.meta is rewritten to the bundle location by bundlers, so storage-postgres must " +
            "not resolve paths from it (docs/bundling.md).",
        },
      ],
    },
  },

  // Tests may be a little looser.
  {
    files: ["**/*.test.ts", "**/*.integration.test.ts", "**/test-support/**"],
    rules: { "@typescript-eslint/no-explicit-any": "off" },
  },

  prettier,
);
