// GENERATED by scripts/generate-templates.mjs — do not edit by hand.
// Source of truth: ../templates/**/*.tmpl. Run `nx run create-skein-js:generate-templates` after
// editing one; src/templates.test.ts fails if this drifts from the sources.

/**
 * Every project template, keyed by its path relative to `templates/` with the `.tmpl` suffix
 * dropped. Values are raw template source — see render-template.ts for the substitution syntax.
 */
export const TEMPLATE_SOURCES: Readonly<Record<string, string>> = {
  "compose.dev.yaml": `# Local services for \`skein start\`, which is durable-only. Start them with:
#   docker compose -f compose.dev.yaml up -d --wait
# \`skein dev\` does not need them — it runs on in-memory drivers.

services:
  postgres:
    # pgvector, not plain postgres: skein's store uses it for semantic search over long-term memory.
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: skein
    # Bound to loopback, not 0.0.0.0. A bare "5432:5432" publishes on every interface, which puts a
    # superuser-credentialed Postgres on whatever network the machine is attached to — and on Linux
    # Docker's DNAT rules are traversed before the filter chain, so a \`ufw deny 5432\` does not save
    # you. Nothing is lost: .env connects over localhost, and \`skein start\` runs on the host.
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d skein"]
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:7-alpine
    # Loopback for the same reason as Postgres above: this Redis has no password, and \`protected-mode\`
    # does not refuse peers arriving through Docker's NAT.
    ports:
      - "127.0.0.1:6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  postgres-data:
`,
  "env.example": `<%_ if (isEnvExample) { _%>
# Copy this file to \`.env\` and fill in what you need. \`.env\` is gitignored, so a fresh clone of this
# project has this file and not that one — this is the copy you start from.
<%_ } else { _%>
# This project's local environment, written for you when the project was scaffolded. Nothing to copy:
# this *is* \`.env\`. (\`.env.example\` is the committed copy, for anyone cloning this repo.)
<%_ } _%>
# \`skein dev\` needs none of it: the \`echo\` graph runs with no credentials and no services.

<%_ if (hasProvider) { _%>
# ---------------------------------------------------------------------------
# The \`agent\` graph's model. Get a key at <%= providerConsoleUrl %>
# ---------------------------------------------------------------------------
# <%= apiKeyEnvVar %>=

# Override the model the agent uses (defaults to <%= defaultModel %>).
# <%= modelEnvVar %>=<%= defaultModel %>

<%_ } _%>
# ---------------------------------------------------------------------------
# Used by \`skein start\`, and by the durable \`dev\` spelling — both need these two.
# These are already the right values for the \`compose.dev.yaml\` in this project — bring it up with
# \`<%= runServices %>\`. Nothing reads them until you do; \`skein dev\` stays in memory regardless.
# ---------------------------------------------------------------------------
POSTGRES_URI=postgresql://postgres:postgres@localhost:5432/skein
REDIS_URI=redis://localhost:6379
`,
  gitignore: `node_modules/
dist/

# Local secrets — .env.example is the checked-in template.
.env
.env.*
!.env.example

# skein's dev state and build artifacts: threads and runs persisted across \`skein dev\` restarts,
# plus the bundled output of \`skein build\` that \`skein start\` runs. Regenerated, never committed.
.skein/

*.log
.DS_Store
`,
  "langgraph.json": `{
  "node_version": "24",
  "graphs": {
    "echo": "./src/echo-graph.ts:graph"<% if (hasProvider) { %>,
    "agent": "./src/agent-graph.ts:graph"<% } %>
  },
  "env": ".env"
}
`,
  "README.md": `# <%= projectName %>

An [Agent Protocol](https://github.com/langchain-ai/agent-protocol) server for your
[LangGraph.js](https://docs.langchain.com/oss/javascript/langgraph/overview) agents, built with
[skein-js](https://skein-js.github.io/skein-js/).

## Develop

\`\`\`bash
<%= runDev %>
\`\`\`

- <http://localhost:2024> — the Agent Protocol API
- <http://localhost:2024/console> — the console: threads, live runs, interrupt approvals, time travel

<%_ if (devIsDurable) { _%>
Postgres and Redis, the same drivers production runs on — start them with \`<%= runServices %>\` first.
Edit a graph and save; the server hot-reloads and keeps your threads.

For the zero-setup path instead — in-memory drivers, nothing to install or start, state restored from
\`.skein/\` across restarts:

\`\`\`bash
<%= runDevAlternate %>
\`\`\`
<%_ } else { _%>
In-memory drivers, nothing to install or start. Edit a graph and save — the server hot-reloads and
keeps your threads. Stop and restart it and your state is restored from \`.skein/\`.

To develop against the drivers production runs on instead — same hot reload, state in Postgres and
Redis rather than \`.skein/\`:

\`\`\`bash
<%= runServices %>   # Postgres + Redis
<%= runDevAlternate %>
\`\`\`
<%_ } _%>

## What's in here

- **\`src/echo-graph.ts\`** — a LangGraph.js graph that echoes your message back. No API key, no
  network. This is the one to edit first.
<%_ if (hasProvider) { _%>
- **\`src/agent-graph.ts\`** — a ReAct agent with a live weather tool. Needs a model key.
<%_ } _%>
- **\`langgraph.json\`** — points skein at your graphs. The same format the LangGraph CLI reads.
- **\`.env\`** — already in place, nothing to copy. Nothing in it is needed for \`dev\`.
  (\`.env.example\` is the committed reference copy; \`.env\` itself is gitignored.)
- **\`compose.dev.yaml\`** — Postgres and Redis, which \`start\` needs.
- **\`tsconfig.json\`** — strict TypeScript, ESM.

<%_ if (hasProvider) { _%>
## Add your model key

The \`echo\` graph runs with no credentials. The \`agent\` graph needs \`<%= apiKeyEnvVar %>\`:

\`.env\` is already here, with the model lines commented out. Uncomment one:

\`\`\`bash
# <%= apiKeyEnvVar %>=your-key-here     ← get one at <%= providerConsoleUrl %>
\`\`\`

Until you do, \`agent\` fails to load and says so, while \`echo\` keeps serving. Save the key in and the
dev server reloads — no restart.

<%_ } _%>
## Talk to it

Any Agent Protocol client works — there is no skein-specific SDK:

\`\`\`ts
import { Client } from "@langchain/langgraph-sdk";

const client = new Client({ apiUrl: "http://localhost:2024" });
const thread = await client.threads.create();
const answer = await client.runs.wait(thread.thread_id, "echo", {
  input: { messages: [{ role: "user", content: "hello" }] },
});
\`\`\`

The same server backs the \`useStream\` React hook — point it at the URL and you have a streaming chat
UI. See [Frontend SDKs](https://skein-js.github.io/skein-js/react-sdk).

## Ship it

\`skein build\` bundles your graphs to plain JavaScript in \`.skein/build\`; \`skein start\` serves that
bundle with no TypeScript toolchain in the loop. That pair is exactly what the production image runs.

\`\`\`bash
<%= runServices %>   # Postgres + Redis
<%= runBuild %>
<%= runStart %>
\`\`\`

Nothing to edit first: \`.env\` already carries the \`POSTGRES_URI\` and \`REDIS_URI\` that match the
\`compose.dev.yaml\` above, and \`skein dev\` ignores them either way.

\`skein start\` is durable-only: it expects \`POSTGRES_URI\` and \`REDIS_URI\`, because that is what makes
runs survive a restart and lets you run more than one instance. For a container instead,
\`npx skein up\` brings up the whole stack, and \`npx skein build\` (without \`--artifact-only\`) produces
the image.

## Next steps

- [Your first agent](https://skein-js.github.io/skein-js/your-first-agent) — from here to deployed
- [Agent Protocol surface](https://skein-js.github.io/skein-js/agent-protocol) — every endpoint
- [Storage](https://skein-js.github.io/skein-js/storage) — long-term memory and checkpoints
- [Deploy](https://skein-js.github.io/skein-js/deploy) — Cloud Run, Fly, Railway, AWS, Kubernetes, a VPS
`,
  "src/agent-graph.ts": `import { tool } from "@langchain/core/tools";
import { <%= modelClass %> } from "<%= modelPackage %>";
import { createAgent } from "langchain";
import { z } from "zod";

/**
 * A ReAct agent whose \`get_weather\` tool fetches live conditions from Open-Meteo
 * (https://open-meteo.com) — a free, no-API-key weather service. Ask e.g. "what's the weather in
 * Nairobi?" and it geocodes the city, pulls the current forecast, and answers from real data.
 * Streams tokens over SSE, so it's the graph to point a \`useStream\` UI at.
 *
 * Requires <%= apiKeyEnvVar %> (get one at <%= providerConsoleUrl %>) for the model — the weather
 * tool itself needs no key. The model is overridable via <%= modelEnvVar %>.
 */

// WMO weather-interpretation codes → short text (the values Open-Meteo returns most often).
const WEATHER_CODES: Record<number, string> = {
  0: "clear sky",
  1: "mainly clear",
  2: "partly cloudy",
  3: "overcast",
  45: "fog",
  51: "light drizzle",
  61: "slight rain",
  63: "rain",
  65: "heavy rain",
  71: "slight snow",
  80: "rain showers",
  95: "thunderstorm",
};

interface GeocodeResponse {
  results?: { latitude: number; longitude: number; name: string; country?: string }[];
}
interface ForecastResponse {
  current?: { temperature_2m: number; wind_speed_10m: number; weather_code: number };
}

const getWeather = tool(
  async ({ city }: { city: string }): Promise<string> => {
    const geo = (await fetch(
      \`https://geocoding-api.open-meteo.com/v1/search?name=\${encodeURIComponent(city)}&count=1\`,
    ).then((response) => response.json())) as GeocodeResponse;
    const place = geo.results?.[0];
    if (!place) return \`I couldn't find a place called "\${city}".\`;

    const forecast = (await fetch(
      \`https://api.open-meteo.com/v1/forecast?latitude=\${place.latitude}&longitude=\${place.longitude}\` +
        \`&current=temperature_2m,wind_speed_10m,weather_code\`,
    ).then((response) => response.json())) as ForecastResponse;
    const current = forecast.current;
    if (!current) return \`I couldn't fetch the current weather for \${place.name}.\`;

    const conditions =
      WEATHER_CODES[current.weather_code] ?? \`weather code \${current.weather_code}\`;
    const where = place.country ? \`\${place.name}, \${place.country}\` : place.name;
    return \`Current weather in \${where}: \${conditions}, \${current.temperature_2m}°C, wind \${current.wind_speed_10m} km/h.\`;
  },
  {
    name: "get_weather",
    description: "Get the current weather for a city, using the free Open-Meteo API.",
    schema: z.object({ city: z.string().describe("City name, e.g. 'Nairobi' or 'Tokyo'") }),
  },
);

// The one credential this project needs, checked by name and up front. Without this the first error
// you see is the model client's own — which does name the variable, but only after a wrapped
// graph-load failure and two stack traces. Say it plainly instead.
const apiKey = process.env.<%= apiKeyEnvVar %>;
if (!apiKey) {
  throw new Error(
    '<%= apiKeyEnvVar %> is not set — the "agent" graph needs it. Uncomment it in .env ' +
      "(get a key at <%= providerConsoleUrl %>) and save; the dev server picks it up on reload. " +
      'The "echo" graph needs no key.',
  );
}

const model = new <%= modelClass %>({
  apiKey,
  model: process.env.<%= modelEnvVar %> ?? "<%= defaultModel %>",
  temperature: 0,
});

export const graph = createAgent({ model, tools: [getWeather] });
`,
  "src/echo-graph.test.ts": `import { HumanMessage } from "@langchain/core/messages";
import { describe, it, expect } from "vitest";

import { graph } from "./echo-graph.js";

describe("echo graph", () => {
  it("echoes the last human message", async () => {
    const result = await graph.invoke({ messages: [new HumanMessage("hello")] });
    const last = result.messages.at(-1);
    expect(last?.content).toBe("echo: hello");
  });

  it("handles an empty conversation without throwing", async () => {
    const result = await graph.invoke({ messages: [] });
    expect(result.messages.at(-1)?.content).toBe("echo: ");
  });
});
`,
  "src/echo-graph.ts": `import { AIMessage, type BaseMessage } from "@langchain/core/messages";
import { MessagesAnnotation, StateGraph } from "@langchain/langgraph";

/**
 * A deterministic, zero-setup graph: it echoes the last human message back.
 * No API key, no network — the perfect thing to point a client at while wiring up skein-js.
 *
 * The three pieces of any LangGraph.js graph are all here:
 *   - state    \`MessagesAnnotation\` — a conversation, appended to on every step
 *   - a node   a function taking state and returning the part of it that changed
 *   - edges    which node runs next; \`__start__\` and \`__end__\` are the entry and exit
 */
function echo(state: typeof MessagesAnnotation.State): { messages: BaseMessage[] } {
  const last = state.messages.at(-1);
  const text = typeof last?.content === "string" ? last.content : "";
  return { messages: [new AIMessage(\`echo: \${text}\`)] };
}

export const graph = new StateGraph(MessagesAnnotation)
  .addNode("echo", echo)
  .addEdge("__start__", "echo")
  .addEdge("echo", "__end__")
  .compile();
`,
  "tsconfig.json": `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "lib": ["ES2023"],
    "strict": true,
    "noUncheckedIndexedAccess": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true,
    "noEmit": true,
    "types": ["node"]
  },
  "include": ["src/**/*.ts"]
}
`,
  "vitest.config.ts": `import { defineConfig } from "vitest/config";

export default defineConfig({
  test: { include: ["src/**/*.test.ts"] },
});
`,
};
