// `skein up` / `build` / `dockerfile` — the Docker half of the LangGraph CLI surface. They share a
// config front-half (read `langgraph.json` for node_version / dockerfile_lines) and generate the
// Dockerfile + compose from the templates here, then shell out to the `docker` CLI.

import { spawn, spawnSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

import { loadConfig, type LanggraphJson } from "@skein-js/config";

import { generateCompose } from "./compose.js";
import { detectPackageManager, generateDockerfile, generateDockerignore } from "./dockerfile.js";

/** Port the server binds inside the container (compose maps the host port onto this). */
const CONTAINER_PORT = 8123;
const DOCKERFILE_NAME = "Dockerfile";
const COMPOSE_NAME = "compose.yaml";
const DOCKERIGNORE_NAME = ".dockerignore";
/** Leading marker every skein-generated asset carries, so we only ever overwrite our own files. */
const GENERATED_MARKER = "# Generated by skein";

interface ConfigContext {
  config: LanggraphJson;
  configDir: string;
}

/** Load + validate `langgraph.json`, resolving its path relative to the cwd. */
async function loadConfigContext(configOption: string): Promise<ConfigContext> {
  const configPath = path.resolve(process.cwd(), configOption);
  const { config, configDir } = await loadConfig({ configPath });
  return { config, configDir };
}

/** Render the Dockerfile for a loaded config. */
function renderDockerfile({ config, configDir }: ConfigContext, port: number): string {
  return generateDockerfile({
    nodeVersion: config.node_version,
    dockerfileLines: config.dockerfile_lines,
    port,
    packageManager: detectPackageManager(configDir),
  });
}

/** A lowercase, docker-safe image name derived from the project directory. */
function defaultImageTag(configDir: string): string {
  const base = path
    .basename(configDir)
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, "-");
  const trimmed = base.replace(/^[-.]+|[-.]+$/g, "");
  return trimmed.length > 0 ? trimmed : "skein-app";
}

/** True when the `docker` CLI is on PATH — a fast preflight so we fail with a clear message. */
function dockerAvailable(): boolean {
  const probe = spawnSync("docker", ["--version"], { stdio: "ignore" });
  return probe.status === 0;
}

function requireDocker(): boolean {
  if (dockerAvailable()) return true;
  console.error("skein: the `docker` CLI was not found on PATH. Install Docker and try again.");
  process.exitCode = 1;
  return false;
}

/** How a spawned process ended: a numeric exit `code`, or a `signal` when it was terminated. */
interface ProcessResult {
  code: number | null;
  signal: NodeJS.Signals | null;
}

/** Spawn a command with inherited stdio; resolves once it exits (never rejects). */
function runToCompletion(command: string, args: string[], cwd: string): Promise<ProcessResult> {
  return new Promise((resolve) => {
    const child = spawn(command, args, { cwd, stdio: "inherit" });
    child.on("error", (error) => {
      console.error(`skein: failed to run \`${command}\`: ${error.message}`);
      resolve({ code: null, signal: null });
    });
    child.on("exit", (code, signal) => resolve({ code, signal }));
  });
}

/** A process succeeded only if it exited 0 on its own (not via a signal). */
function succeeded(result: ProcessResult): boolean {
  return result.code === 0 && result.signal === null;
}

/** Ctrl-C / termination — the normal way to stop a long-running `docker compose up`. */
function wasInterrupted(result: ProcessResult): boolean {
  return result.code === 130 || result.signal === "SIGINT" || result.signal === "SIGTERM";
}

/** Human-readable exit description for error messages. */
function describeExit(result: ProcessResult): string {
  return result.signal !== null ? `killed by ${result.signal}` : `exit ${result.code}`;
}

/**
 * Write a generated asset, but never clobber a file the user wrote by hand: if the target exists
 * and lacks the skein-generated marker, leave it untouched. Returns whether we wrote it (so callers
 * can still build against a user's own Dockerfile).
 */
function writeGeneratedFile(file: string, contents: string): "wrote" | "kept-user" {
  const name = path.basename(file);
  if (existsSync(file) && !readFileSync(file, "utf8").startsWith(GENERATED_MARKER)) {
    console.log(`skein: ${name} exists and wasn't generated by skein — using it as-is.`);
    return "kept-user";
  }
  writeFileSync(file, contents);
  console.log(`skein: wrote ${name}.`);
  return "wrote";
}

export interface DockerfileCommandOptions {
  config: string;
  /** Write to this path instead of stdout. */
  output?: string;
}

/** `skein dockerfile` — emit the generated Dockerfile to stdout (or `--output`). */
export async function runDockerfile(options: DockerfileCommandOptions): Promise<void> {
  const context = await loadConfigContext(options.config);
  const contents = renderDockerfile(context, CONTAINER_PORT);
  if (options.output !== undefined) {
    const target = path.resolve(process.cwd(), options.output);
    writeFileSync(target, contents);
    console.log(`skein: wrote ${target}.`);
    return;
  }
  process.stdout.write(contents);
}

export interface BuildCommandOptions {
  config: string;
  /** Image tag; defaults to the project directory name. */
  tag?: string;
}

/** `skein build` — write the Docker assets (never clobbering user files) and build via `docker build`. */
export async function runBuild(options: BuildCommandOptions): Promise<void> {
  const context = await loadConfigContext(options.config);
  if (!requireDocker()) return;

  const dockerfilePath = path.join(context.configDir, DOCKERFILE_NAME);
  writeGeneratedFile(dockerfilePath, renderDockerfile(context, CONTAINER_PORT));
  writeGeneratedFile(path.join(context.configDir, DOCKERIGNORE_NAME), generateDockerignore());

  const tag = options.tag ?? defaultImageTag(context.configDir);
  console.log(`skein: building image "${tag}"…`);
  const result = await runToCompletion(
    "docker",
    ["build", "-t", tag, "-f", dockerfilePath, "."],
    context.configDir,
  );
  if (!succeeded(result)) {
    console.error(`skein: docker build failed (${describeExit(result)}).`);
    process.exitCode = 1;
    return;
  }
  console.log(`skein: built image "${tag}".`);
}

export interface UpCommandOptions {
  config: string;
  port: number;
  host: string;
}

/** `skein up` — generate compose + Dockerfile (if absent) and bring up app + Postgres + Redis. */
export async function runUp(options: UpCommandOptions): Promise<void> {
  const context = await loadConfigContext(options.config);
  if (!requireDocker()) return;

  writeGeneratedFile(
    path.join(context.configDir, DOCKERFILE_NAME),
    renderDockerfile(context, CONTAINER_PORT),
  );
  writeGeneratedFile(path.join(context.configDir, DOCKERIGNORE_NAME), generateDockerignore());
  writeGeneratedFile(
    path.join(context.configDir, COMPOSE_NAME),
    generateCompose({ hostPort: options.port, host: options.host, containerPort: CONTAINER_PORT }),
  );

  console.log(
    `skein: bringing up the stack (app + Postgres + Redis) on http://${options.host}:${options.port}…`,
  );
  const result = await runToCompletion(
    "docker",
    ["compose", "-f", COMPOSE_NAME, "up", "--build"],
    context.configDir,
  );
  // Ctrl-C is the normal way to stop `compose up`, so only a genuine non-zero exit is an error.
  if (!succeeded(result) && !wasInterrupted(result)) {
    console.error(`skein: docker compose up failed (${describeExit(result)}).`);
    process.exitCode = 1;
  }
}
