// Generate a Docker Compose file for `skein up`: the app plus Postgres (with pgvector) and Redis.
// The topology mirrors production (docs/runs-and-redis.md) so `up` is a faithful local stand-in.

export interface ComposeOptions {
  /** Host port to publish the app on. */
  hostPort: number;
  /** Host interface to bind; when set and not 0.0.0.0 it prefixes the published port. */
  host?: string;
  /** Port the app binds inside the container. */
  containerPort: number;
}

/** Build the `ports` mapping, binding to a specific host interface when one is requested. */
function portMapping(options: ComposeOptions): string {
  const { hostPort, host, containerPort } = options;
  const bindsAllInterfaces = host === undefined || host === "0.0.0.0" || host === "::";
  return bindsAllInterfaces
    ? `"${hostPort}:${containerPort}"`
    : `"${host}:${hostPort}:${containerPort}"`;
}

/**
 * Render `compose.yaml`. Postgres uses the `pgvector/pgvector` image — the store's init migration
 * runs `CREATE EXTENSION vector`, so the stock `postgres` image would fail. Healthchecks gate the
 * app's `depends_on` so it never boots before its backends are accepting connections.
 */
export function generateCompose(options: ComposeOptions): string {
  const ports = portMapping(options);
  return `# Generated by skein — regenerated by \`skein up\`. Edit with care.
services:
  app:
    build: .
    # Reap zombies + forward signals with an init process (PID 1), so graph-spawned children don't
    # accumulate; the app itself still handles SIGTERM for graceful shutdown.
    init: true
    ports:
      - ${ports}
    environment:
      # The container CMD passes no --port; it binds $PORT (as a hosting platform would inject).
      # Set it here so the app listens on the port the mapping above publishes.
      PORT: "${options.containerPort}"
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/skein
      REDIS_URL: redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: skein
    volumes:
      - skein-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d skein"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  redis:
    image: redis:7
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  skein-pgdata:
`;
}
