// Generate a Docker Compose file for `skein up`: the app plus Postgres (with pgvector) and Redis.
// The topology mirrors production (docs/runs-and-redis.md) so `up` is a faithful local stand-in.

export interface ComposeOptions {
  /** Host port to publish the app on. */
  hostPort: number;
  /** Host interface to bind; when set and not 0.0.0.0 it prefixes the published port. */
  host?: string;
  /** Port the app binds inside the container. */
  containerPort: number;
  /**
   * Absolute path to an `.npmrc`, wired in as a build secret (`id=npmrc`) so the app image can
   * authenticate a private-registry install. When absent, no secret is emitted.
   */
  npmrcPath?: string;
}

/** Build the `ports` mapping, binding to a specific host interface when one is requested. */
function portMapping(options: ComposeOptions): string {
  const { hostPort, host, containerPort } = options;
  const bindsAllInterfaces = host === undefined || host === "0.0.0.0" || host === "::";
  return bindsAllInterfaces
    ? `"${hostPort}:${containerPort}"`
    : `"${host}:${hostPort}:${containerPort}"`;
}

/**
 * Render `compose.yaml`. Postgres uses the `pgvector/pgvector` image — the store's init migration
 * runs `CREATE EXTENSION vector`, so the stock `postgres` image would fail. Healthchecks gate the
 * app's `depends_on` so it never boots before its backends are accepting connections.
 */
export function generateCompose(options: ComposeOptions): string {
  const ports = portMapping(options);
  // With an `.npmrc` the app build mounts it as the `id=npmrc` secret the Dockerfile expects; the
  // top-level `secrets:` block below points that id at the file on the host. Without one, keep the
  // terse `build: .` and emit no secrets block.
  const appBuild = options.npmrcPath
    ? `build:
      context: .
      secrets:
        - npmrc`
    : `build: .`;
  const secretsBlock = options.npmrcPath
    ? `
secrets:
  npmrc:
    file: ${JSON.stringify(options.npmrcPath)}
`
    : "";
  return `# Generated by skein — regenerated by \`skein up\`. Edit with care.
services:
  app:
    ${appBuild}
    # Reap zombies + forward signals with an init process (PID 1), so graph-spawned children don't
    # accumulate; the app itself still handles SIGTERM for graceful shutdown.
    init: true
    ports:
      - ${ports}
    environment:
      # The container CMD passes no --port; it binds $PORT (as a hosting platform would inject), and
      # falls back to this same port anyway. Set explicitly so the mapping above stays correct even
      # if a host port is published that differs from the port the container listens on.
      PORT: "${options.containerPort}"
      POSTGRES_URI: postgresql://postgres:postgres@postgres:5432/skein
      REDIS_URI: redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    # Longer than Docker's 10s default so the app can finish its shutdown: it drains in-flight runs
    # for SKEIN_SHUTDOWN_GRACE_MS, then aborts the stragglers so they settle to a terminal status.
    # 10s leaves no headroom the moment that window is raised, and a SIGKILL mid-abort is exactly
    # what leaves a run stuck in a non-terminal state.
    stop_grace_period: 30s

  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: skein
    volumes:
      - skein-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d skein"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  redis:
    image: redis:7
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  skein-pgdata:
${secretsBlock}`;
}
