// Generate the Dockerfile for the pre-built production image. `skein build`/`up` bundle the project's
// TypeScript graphs (+ auth/embed) into a self-contained `.skein/build` artifact of plain JS on the
// host (see ../bundle/bundle-project.ts); this Dockerfile is generated INTO that artifact dir, and the
// image simply installs the artifact's pinned production dependencies and runs `skein start` over the
// compiled output. No vite/tsx, no devDependencies, no runtime TypeScript transform — the image
// carries only what it runs. The artifact ships its own `package.json`, so package-manager detection
// and the user's lockfile are irrelevant here; a single `npm install --omit=dev` is deterministic
// because every dependency is exact-pinned.

/** Node major version → base image tag; falls back to 20 (the examples' pin). */
function baseImage(nodeVersion: string | undefined): string {
  const major = nodeVersion?.trim().match(/^\d+/)?.[0] ?? "20";
  return `node:${major}-slim`;
}

export interface DockerfileOptions {
  /** `node_version` from the config (major version); defaults to 20. */
  nodeVersion?: string;
  /** `dockerfile_lines` from the config, appended verbatim after the base layers. */
  dockerfileLines?: readonly string[];
  /** Port the server binds inside the container. */
  port: number;
}

/**
 * Render a `.dockerignore` for the artifact build context. The artifact is self-contained (bundled
 * JS + a pinned `package.json` + the production `langgraph.json`/`schemas.json`), so this mainly keeps
 * the generated Docker assets and any locally-installed `node_modules` out of the image — deps are
 * (re)installed by the build's install step.
 */
export function generateDockerignore(): string {
  return [
    "# Generated by skein — regenerated by `skein build` / `skein up`.",
    ".git",
    "node_modules",
    ".env",
    ".env.*",
    // Never bake a registry credential into a layer — it's supplied via a BuildKit secret at install.
    ".npmrc",
    ".npmrc.*",
    "Dockerfile",
    "compose.yaml",
    ".dockerignore",
    "npm-debug.log*",
    "",
  ].join("\n");
}

/** Render the Dockerfile text for `skein build` / `skein dockerfile`, run against the build artifact. */
export function generateDockerfile(options: DockerfileOptions): string {
  const { nodeVersion, dockerfileLines = [], port } = options;

  const lines = [
    // The syntax directive must be the first line to be honored — it enables the RUN cache mount.
    `# syntax=docker/dockerfile:1`,
    `# Generated by skein — do not edit by hand (regenerated by \`skein build\` / \`skein up\`).`,
    // The build context must be a skein artifact dir (bundled JS + pinned package.json + schemas.json),
    // which `skein build`/`up` create under `.skein/build`. Building this Dockerfile against a raw
    // project dir will fail — run `skein build` instead of `docker build` by hand.
    `# Build context: a \`.skein/build\` artifact produced by \`skein build\` (not the project root).`,
    `FROM ${baseImage(nodeVersion)}`,
    `WORKDIR /app`,
    ``,
    // Install prod deps first for layer caching: the artifact's pinned package.json changes rarely,
    // so this layer is reused across rebuilds while only the bundle layer below re-runs. The BuildKit
    // cache mount keeps the npm cache out of the committed layer. The `npmrc` secret mount lets private
    // scoped deps authenticate against a private/authenticated registry without baking a token into any
    // layer; it is optional (BuildKit secrets are not required by default), so a public-registry build
    // that passes no secret is unaffected. Supply it via `skein build --npmrc <path>` or, for the
    // standalone Dockerfile, `docker build --secret id=npmrc,src=<path>`.
    `# Install the artifact's pinned production dependencies (exact versions — deterministic).`,
    `COPY package.json ./`,
    `RUN --mount=type=cache,target=/root/.npm \\`,
    `    --mount=type=secret,id=npmrc,target=/app/.npmrc \\`,
    `    npm install --omit=dev --omit=optional --no-audit --no-fund`,
    ``,
    `# Copy the pre-built artifact (bundled JS graphs, production langgraph.json, baked schemas).`,
    `COPY . .`,
    ``,
    `ENV NODE_ENV=production`,
    // The bundle ships sourcemaps; enable them so stack traces map back to the original TypeScript.
    `ENV NODE_OPTIONS=--enable-source-maps`,
    `EXPOSE ${port}`,
    // Liveness probe against skein's `/ok` endpoint, targeting the same port the server binds. PORT
    // is resolved exactly as `envPort` resolves it — integer, in range, blank counts as unset —
    // rather than by truthiness, so a malformed value (`PORT=8080a`, `PORT=0`) has the probe and the
    // server agree on the fallback instead of probing a URL the server never bound.
    `HEALTHCHECK --interval=30s --timeout=3s --start-period=20s --retries=3 \\`,
    `    CMD node -e "const r=Number(process.env.PORT);const p=Number.isInteger(r)&&r>=0&&r<=65535?r:${port};fetch('http://127.0.0.1:'+p+'/ok').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"`,
    // Run unprivileged. The bundle writes nothing to disk, and /app is world-readable, so no chown.
    `USER node`,
    ...dockerfileLines,
    ``,
    `# Serve the compiled artifact against Postgres + Redis (POSTGRES_URI / REDIS_URI from the env).`,
    `# No --port: the server binds $PORT when the platform injects one (Railway/Fly/Render/Cloud Run),`,
    `# else \`skein start\`'s default — the port EXPOSEd above, so a bare \`docker run -p ${port}:${port}\``,
    `# works too.`,
    `#`,
    `# Invoked as \`node <entry>\` rather than \`npx skein\` so that **node itself is PID 1**. Under npx,`,
    `# PID 1 is npm, which forwards SIGTERM to a \`sh -c\` child and exits immediately — the server is`,
    `# killed mid-shutdown and in-flight runs are left stranded in a non-terminal status. Exec form`,
    `# (no shell) keeps the signal path direct, so SIGTERM reaches skein's graceful-shutdown handler.`,
    // Absolute, so a `dockerfile_lines` entry that changes WORKDIR (spliced in just above) can't
    // leave the CMD resolving against the wrong directory.
    `CMD ["node", "/app/node_modules/skein-js/dist/index.js", "start", "--store", "postgres", "--queue", "redis", "--host", "0.0.0.0"]`,
  ];
  return `${lines.join("\n")}\n`;
}
