#!/usr/bin/env node
// Generate `src/assets.generated.ts` — the built console SPA, compiled into the JS bundle.
//
// Why this exists: a library must not read package-relative files at runtime. Bundlers rewrite
// `import.meta.url` to the *output* location, so anything resolved from it breaks the moment a
// consumer bundles their server (Next.js, webpack/rspack, esbuild). @skein-js/storage-postgres hit
// exactly this with its migrations/ directory and solved it by compiling the SQL in; the console has
// the same constraint with a bigger payload, and takes the same route. See docs/bundling.md.
//
// Text assets (HTML/JS/CSS/SVG) are embedded as UTF-8 string literals so the generated module stays
// diffable and gzips well; anything binary is embedded as base64. The build output is the input, so
// run `nx build console-ui` first — `nx build console` does that for you via the target graph.

import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { format, resolveConfig } from "prettier";

const packageRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const uiDistDir = path.join(packageRoot, "ui", "dist");
const outputFile = path.join(packageRoot, "src", "assets.generated.ts");

/** Content types the console actually emits. Unknown extensions are refused rather than guessed. */
const CONTENT_TYPES = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".ico": "image/x-icon",
  ".png": "image/png",
  ".webp": "image/webp",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
};

/** Extensions embedded as UTF-8 text; everything else is base64. */
const TEXT_EXTENSIONS = new Set([".html", ".js", ".css", ".json", ".svg"]);

/** Every file under `dir`, as paths relative to it, with `/` separators and sorted for stability. */
async function listFiles(dir, prefix = "") {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const relativePath = prefix === "" ? entry.name : `${prefix}/${entry.name}`;
    if (entry.isDirectory()) {
      files.push(...(await listFiles(path.join(dir, entry.name), relativePath)));
    } else {
      files.push(relativePath);
    }
  }
  return files.sort();
}

async function main() {
  let files;
  try {
    files = await listFiles(uiDistDir);
  } catch (error) {
    if (error.code === "ENOENT") {
      throw new Error(
        `No console build at ${uiDistDir}. Run \`nx build console-ui\` first ` +
          `(\`nx build console\` does it for you).`,
      );
    }
    throw error;
  }

  if (!files.includes("index.html")) {
    throw new Error(`The console build at ${uiDistDir} has no index.html — nothing to serve.`);
  }

  const assets = [];
  for (const file of files) {
    const extension = path.extname(file).toLowerCase();
    const contentType = CONTENT_TYPES[extension];
    if (contentType === undefined) {
      throw new Error(
        `No content type for "${file}". Add ${extension} to CONTENT_TYPES in ` +
          `scripts/generate-assets.mjs — serving it as the wrong type is worse than failing here.`,
      );
    }
    const bytes = await readFile(path.join(uiDistDir, file));
    const isText = TEXT_EXTENSIONS.has(extension);
    assets.push({
      file,
      contentType,
      encoding: isText ? "utf8" : "base64",
      body: isText ? bytes.toString("utf8") : bytes.toString("base64"),
      byteLength: bytes.byteLength,
    });
  }

  const totalBytes = assets.reduce((total, asset) => total + asset.byteLength, 0);
  const entries = assets
    .map(
      (asset) =>
        `  ${JSON.stringify(asset.file)}: {\n` +
        `    contentType: ${JSON.stringify(asset.contentType)},\n` +
        `    encoding: ${JSON.stringify(asset.encoding)},\n` +
        `    byteLength: ${asset.byteLength},\n` +
        `    body: ${JSON.stringify(asset.body)},\n` +
        `  },`,
    )
    .join("\n");

  const source = `// GENERATED by scripts/generate-assets.mjs — do not edit.
// Source: packages/console/ui (built by \`nx build console-ui\`). Regenerate with
// \`nx run console:generate-assets\`.
//
// ${assets.length} files, ${totalBytes} bytes uncompressed.

import type { ConsoleAsset } from "./assets.js";

export const CONSOLE_ASSETS: Readonly<Record<string, ConsoleAsset>> = {
${entries}
};

/** Total uncompressed size of the bundled console, in bytes. Pinned by assets.test.ts. */
export const CONSOLE_ASSETS_BYTES = ${totalBytes};
`;

  const prettierConfig = await resolveConfig(outputFile);
  const formatted = await format(source, { ...prettierConfig, filepath: outputFile });
  await writeFile(outputFile, formatted, "utf8");
  console.log(
    `generate-assets: ${assets.length} files, ${(totalBytes / 1024).toFixed(1)} kB → src/assets.generated.ts`,
  );
}

await main();
